obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_CORE)   += synaptics_dsx/
obj-$(CONFIG_TOUCHSCREEN_NT36672)   += nt36672/
obj-$(CONFIG_VITURALSAR)			+= vituralsar_driver.o
obj-$(CONFIG_TOUCHSCREEN_FTS_MI8953) += focaltech_touch/
obj-$(CONFIG_TOUCHSCREEN_GT9XX) += gt9xx/
obj-$(CONFIG_TOUCHSCREEN_SYSCTL_MI8953) += ts_sysctl.o